/*
Deployment script for IM.BulkInsert.DB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "IM.BulkInsert.DB"
:setvar DefaultFilePrefix "IM.BulkInsert.DB"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER12\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER12\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
-- update scripts

IF NOT EXISTS 
    (SELECT name  
     FROM master.sys.server_principals
     WHERE name = 'bulkinsert')
BEGIN
    CREATE LOGIN bulkinsert WITH PASSWORD = 'bulkinsertpassword'
END

GO

-- Creates a database user for the login created above.
IF NOT EXISTS 
	(SELECT * FROM sys.sysusers WHERE name='bulkinsert')
BEGIN
	CREATE USER bulkinsert FOR LOGIN bulkinsert;
	EXEC sp_addrolemember 'db_owner', 'bulkinsert'
END

GO

GO
PRINT N'Update complete.';


GO
